# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_bios735_rcpp_hello_world', PACKAGE = 'bios735')
}

one_or_exp <- function(x) {
    .Call('_bios735_one_or_exp', PACKAGE = 'bios735', x)
}

